apiVersion: v1
kind: Service
metadata:
  name: {{ include "askloud-gui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "askloud-gui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "askloud-gui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
